import { Product, Category, Testimonial } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Canecas', image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Coffee' },
  { id: '2', name: 'Camisetas', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Shirt' },
  { id: '3', name: 'Cadernos', image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Book' },
  { id: '4', name: 'Squeezes', image: 'https://images.unsplash.com/photo-1602143399827-7211aa3a7935?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Droplets' },
  { id: '5', name: 'Brindes', image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Gift' },
  { id: '6', name: 'Kits', image: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Package' },
  { id: '7', name: 'Almofadas', image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Cloud' },
  { id: '8', name: 'Chaveiros', image: 'https://images.unsplash.com/photo-1584567528189-a25724ff67b1?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Key' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Caneca Cerâmica Personalizada 325ml',
    price: 34.90,
    oldPrice: 45.00,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&q=80&w=400&h=400',
    tag: 'Mais Vendido',
    rating: 4.8,
    reviews: 124,
    description: 'Nossa caneca de cerâmica personalizada é perfeita para o seu café da manhã ou para presentear alguém especial. Com acabamento em alto brilho e impressão de alta definição, ela garante durabilidade e cores vibrantes.',
    features: ['Cerâmica de alta qualidade', 'Capacidade de 325ml', 'Pode ir ao micro-ondas e lava-louças', 'Impressão digital em alta definição'],
    categoryId: '1',
  },
  {
    id: 'p2',
    name: 'Camiseta Algodão Premium Personalizada',
    price: 59.90,
    oldPrice: 79.00,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=400&h=400',
    tag: 'Oferta',
    rating: 4.9,
    reviews: 89,
    description: 'Camiseta confeccionada em algodão 100% premium, fio 30.1 penteado. Conforto e durabilidade aliados a uma estampa personalizada com a sua arte favorita.',
    features: ['100% Algodão Penteado', 'Costura reforçada', 'Toque macio e confortável', 'Estampa durável que não racha'],
    categoryId: '2',
  },
  {
    id: 'p3',
    name: 'Caderno A5 Capa Dura Personalizado',
    price: 42.90,
    image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&q=80&w=400&h=400',
    rating: 4.7,
    reviews: 56,
    description: 'Ideal para anotações, estudos ou como diário. O caderno capa dura personalizado une elegância e praticidade com um acabamento sofisticado.',
    features: ['Capa dura com laminação fosca', '80 folhas pautadas', 'Tamanho A5 (15x21cm)', 'Elástico para fechamento'],
    categoryId: '3',
  },
  {
    id: 'p4',
    name: 'Squeeze Alumínio 600ml Personalizado',
    price: 39.90,
    oldPrice: 49.90,
    image: 'https://images.unsplash.com/photo-1602143399827-7211aa3a7935?auto=format&fit=crop&q=80&w=400&h=400',
    tag: 'Novo',
    rating: 4.6,
    reviews: 34,
    description: 'Mantenha-se hidratado com estilo. Nosso squeeze de alumínio é leve, resistente e mantém sua bebida fresca por mais tempo.',
    features: ['Alumínio resistente', 'Capacidade de 600ml', 'Tampa com bico articulado', 'Mosquetão incluso'],
    categoryId: '4',
  },
  {
    id: 'p5',
    name: 'Kit Escritório Personalizado (3 itens)',
    price: 129.90,
    oldPrice: 159.00,
    image: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?auto=format&fit=crop&q=80&w=400&h=400',
    tag: 'Kit Premium',
    rating: 5.0,
    reviews: 12,
    description: 'O kit perfeito para organizar seu espaço de trabalho ou presentear colaboradores. Inclui caderno, caneta e caneca, todos personalizados.',
    features: ['Caderno Capa Dura', 'Caneta Metal Gravada', 'Caneca de Cerâmica', 'Embalagem especial para presente'],
    categoryId: '6',
  },
  {
    id: 'p6',
    name: 'Almofada Decorativa Personalizada 40x40',
    price: 49.90,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&q=80&w=400&h=400',
    rating: 4.8,
    reviews: 45,
    description: 'Dê um toque especial à sua sala ou quarto com nossas almofadas personalizadas. Super macias e com estampa de alta qualidade.',
    features: ['Tecido Oxford/Poliéster', 'Enchimento de fibra siliconada', 'Capa com zíper invisível', 'Tamanho 40x40cm'],
    categoryId: '7',
  },
  {
    id: 'p7',
    name: 'Agenda 2024 Personalizada Luxo',
    price: 64.90,
    oldPrice: 89.90,
    image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&q=80&w=400&h=400',
    tag: 'Destaque',
    rating: 4.9,
    reviews: 67,
    description: 'Organize seu ano com sofisticação. Nossa agenda luxo possui acabamento premium e páginas dedicadas ao seu planejamento diário.',
    features: ['Capa dura com hot stamping', 'Um dia por página', 'Fita marca página', 'Dados pessoais e calendários'],
    categoryId: '3',
  },
  {
    id: 'p8',
    name: 'Chaveiro Metal Personalizado Gravado',
    price: 19.90,
    image: 'https://images.unsplash.com/photo-1584567528189-a25724ff67b1?auto=format&fit=crop&q=80&w=400&h=400',
    rating: 4.5,
    reviews: 23,
    description: 'Um detalhe que faz a diferença. Chaveiro de metal resistente com gravação a laser de alta precisão.',
    features: ['Metal cromado', 'Gravação a laser permanente', 'Argola reforçada', 'Leve e elegante'],
    categoryId: '8',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Mariana Silva',
    text: 'As canecas ficaram perfeitas! A qualidade da impressão é impressionante e chegou super rápido.',
    rating: 5,
    avatar: 'https://i.pravatar.cc/150?u=mariana',
  },
  {
    id: 't2',
    name: 'Ricardo Oliveira',
    text: 'Fizemos as camisetas para a empresa e todos adoraram. Atendimento nota 10!',
    rating: 5,
    avatar: 'https://i.pravatar.cc/150?u=ricardo',
  },
  {
    id: 't3',
    name: 'Ana Paula',
    text: 'Os cadernos são lindos e a capa tem um toque muito premium. Com certeza comprarei mais.',
    rating: 5,
    avatar: 'https://i.pravatar.cc/150?u=ana',
  },
];
