import { Product, Category, Testimonial } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Cozinha', image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Utensils' },
  { id: '2', name: 'Tecnologia', image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Smartphone' },
  { id: '3', name: 'Decoração', image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Home' },
  { id: '4', name: 'Beleza', image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Sparkles' },
  { id: '5', name: 'Organização', image: 'https://images.unsplash.com/photo-1594485812914-6c1398c8994b?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Box' },
  { id: '6', name: 'Pets', image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Dog' },
  { id: '7', name: 'Moda', image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&q=80&w=300&h=300', icon: 'Shirt' },
  { id: '8', name: 'Papelaria', image: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&q=80&w=300&h=300', icon: 'PenTool' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Mini Processador de Alimentos Elétrico USB',
    price: 49.90,
    oldPrice: 89.00,
    image: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&q=80&w=400&h=400',
    tag: 'Mais Vendido',
    rating: 4.8,
    reviews: 1240,
    description: 'O mini processador elétrico é prático e eficiente. Com carregamento USB, ele facilita o preparo de temperos e alimentos em segundos.',
    features: ['Carregamento USB', 'Lâminas de aço inox', 'Fácil de lavar', 'Portátil e compacto'],
    categoryId: '1',
    affiliateUrl: 'https://shopee.com.br/product/123/456',
  },
  {
    id: 'p2',
    name: 'Luminária de Mesa LED com Carregador por Indução',
    price: 129.90,
    oldPrice: 199.00,
    image: 'https://images.unsplash.com/photo-1534073828943-f801091bb18c?auto=format&fit=crop&q=80&w=400&h=400',
    tag: 'Oferta',
    rating: 4.9,
    reviews: 890,
    description: 'Luminária moderna com ajuste de brilho e carregamento sem fio para o seu smartphone. Perfeita para o seu home office.',
    features: ['Carregamento Wireless', '3 níveis de luz', 'Design minimalista', 'Touch control'],
    categoryId: '2',
    affiliateUrl: 'https://amazon.com.br/product/123/456',
  },
  {
    id: 'p3',
    name: 'Organizador de Geladeira com Alça',
    price: 22.90,
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400&h=400',
    rating: 4.7,
    reviews: 560,
    description: 'Mantenha sua geladeira organizada e ganhe espaço com esses cestos práticos e transparentes.',
    features: ['Material resistente', 'Transparente', 'Fácil de limpar', 'Empilhável'],
    categoryId: '5',
    affiliateUrl: 'https://shopee.com.br/product/123/456',
  },
  {
    id: 'p4',
    name: 'Umidificador de Ar Ultrassônico com LED',
    price: 59.90,
    oldPrice: 99.90,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&q=80&w=400&h=400',
    tag: 'Novo',
    rating: 4.6,
    reviews: 340,
    description: 'Melhore a qualidade do ar e decore seu ambiente com este umidificador silencioso e com luzes RGB.',
    features: ['Silencioso', 'Luzes LED', 'Capacidade 300ml', 'Alimentação USB'],
    categoryId: '3',
    affiliateUrl: 'https://amazon.com.br/product/123/456',
  },
  {
    id: 'p5',
    name: 'Kit 10 Pincéis de Maquiagem Profissional',
    price: 39.90,
    oldPrice: 79.00,
    image: 'https://images.unsplash.com/photo-1522338223543-98603f06ec6d?auto=format&fit=crop&q=80&w=400&h=400',
    tag: 'Destaque',
    rating: 5.0,
    reviews: 1200,
    description: 'Cerdas macias e sintéticas para uma aplicação perfeita da sua maquiagem. Kit completo para rosto e olhos.',
    features: ['Cerdas sintéticas', 'Cabo ergonômico', 'Fácil de limpar', 'Estojo incluso'],
    categoryId: '4',
    affiliateUrl: 'https://shopee.com.br/product/123/456',
  },
  {
    id: 'p6',
    name: 'Escova de Limpeza Elétrica 5 em 1',
    price: 69.90,
    image: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&q=80&w=400&h=400',
    rating: 4.8,
    reviews: 450,
    description: 'Limpe azulejos, pias e fogões sem esforço com esta escova elétrica potente e versátil.',
    features: ['5 cabeças diferentes', 'Sem fio', 'Recarregável', 'À prova d\'água'],
    categoryId: '1',
    affiliateUrl: 'https://amazon.com.br/product/123/456',
  },
  {
    id: 'p7',
    name: 'Bebedouro Fonte para Gatos e Cães',
    price: 84.90,
    oldPrice: 129.90,
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=400&h=400',
    tag: 'Pet Lover',
    rating: 4.9,
    reviews: 670,
    description: 'Água sempre fresca e filtrada para o seu pet. Estimula a hidratação e previne doenças renais.',
    features: ['Filtro de carvão ativado', 'Silencioso', 'Capacidade 2L', 'Bivolt'],
    categoryId: '6',
    affiliateUrl: 'https://shopee.com.br/product/123/456',
  },
  {
    id: 'p8',
    name: 'Mini Selador de Embalagens Térmico',
    price: 15.90,
    image: 'https://images.unsplash.com/photo-1589365278144-c9e705f843ba?auto=format&fit=crop&q=80&w=400&h=400',
    rating: 4.5,
    reviews: 230,
    description: 'Mantenha seus alimentos frescos por muito mais tempo selando as embalagens de forma rápida e segura.',
    features: ['Térmico', 'Portátil', 'Funciona com pilhas', 'Base magnética'],
    categoryId: '1',
    affiliateUrl: 'https://amazon.com.br/product/123/456',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Mariana Silva',
    text: 'As canecas ficaram perfeitas! A qualidade da impressão é impressionante e chegou super rápido.',
    rating: 5,
    avatar: 'https://i.pravatar.cc/150?u=mariana',
  },
  {
    id: 't2',
    name: 'Ricardo Oliveira',
    text: 'Fizemos as camisetas para a empresa e todos adoraram. Atendimento nota 10!',
    rating: 5,
    avatar: 'https://i.pravatar.cc/150?u=ricardo',
  },
  {
    id: 't3',
    name: 'Ana Paula',
    text: 'Os cadernos são lindos e a capa tem um toque muito premium. Com certeza comprarei mais.',
    rating: 5,
    avatar: 'https://i.pravatar.cc/150?u=ana',
  },
];
